# primitive_functions/display_information.py

def display_plan(plan_obj):
    """
    Nicely prints out the disaster preparedness plan
    generated by create_preparedness_workflow().

    Parameters:
    -----------
    plan_obj : dict
        Should contain keys:
        - location
        - policy
        - generated_at (UTC timestamp)
        - plan (list of steps)
    """

    print("\n=== Disaster Preparedness Plan ===")
    print(f"Location: {plan_obj.get('location')}")
    print(f"Policy: {plan_obj.get('policy')}")
    print(f"Generated at (UTC): {plan_obj.get('generated_at')}")

    print("\nPlan Steps:")
    for i, step in enumerate(plan_obj.get("plan", []), start=1):
        print(f"{i}. {step}")

    print("\n(End of Plan)\n")
